modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"

[[mods]] #mandatory
modId="autosmelt" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Auto-Smelt" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/auto-smelt"
updateJSONURL="https://onvoid.net/autosmelt/update.json"
logoFile="autosmelt.png" #optional
logoBlur=false
credits="onVoid" #optional
authors="onVoid" #optional
description="Adds a simple enchantment to automatically smelt broken blocks."
itemIcon="minecraft:enchanted_book"
configBackground="minecraft:textures/block/bookshelf.png"

[[dependencies.simplicity]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    ordering="NONE"
    side="BOTH"