modLoader="javafml"
loaderVersion="[41,)"
license="MIT License"
issueTrackerURL="https://github.com/brdle/Auto-Smelt/issues"

[[mods]] #mandatory
modId="autosmelt" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Auto-Smelt" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/auto-smelt"
updateJSONURL="https://onvoid.net/autosmelt/update.json"
logoFile="autosmelt.png" #optional
logoBlur=false
credits="brdle" #optional
authors="brdle" #optional
description="Adds a simple enchantment to automatically smelt drops from anything broken or killed."
itemIcon="minecraft:enchanted_book"
configBackground="minecraft:textures/block/bookshelf.png"

[[dependencies.autosmelt]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41,)" #mandatory
    ordering="NONE"
    side="BOTH"