modLoader="javafml"
loaderVersion="[39,)"
license="MIT License"
issueTrackerURL="https://github.com/brdle/Auto-Smelt/issues"

[[mods]]
modId="autosmelt"
version="${file.jarVersion}"
displayName="Auto-Smelt"
displayURL="https://www.curseforge.com/minecraft/mc-mods/auto-smelt"
updateJSONURL="https://onvoid.net/autosmelt/update.json"
logoFile="autosmelt.png"
logoBlur=false
credits="brdle"
authors="brdle"
description="Adds a simple enchantment to automatically smelt drops from anything broken or killed."
itemIcon="minecraft:enchanted_book"
configBackground="minecraft:textures/block/bookshelf.png"

[[dependencies.autosmelt]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"